server:
  port: 8090

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/jpa
    password: 'google'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update


